/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Assert;
import org.junit.Test;

import static org.junit.Assert.*;

public class WeatherTest {
    @Test
    public void testDesc() {
        Weather classUnderTest = new Weather("kelowna");


        assertEquals("-14.35", classUnderTest.getTemp());
    }

    @Test
    public void testGetWeatherMain() {
        Weather classUnderTest = new Weather("kelowna");
        assertEquals("Clear", classUnderTest.getWeatherMain());
    }

    @Test
    public void testGetTemp() {
        Weather f = new Weather("Kelowna");
        assertEquals("clear sky", f.getWeatherDesc());
    }
}
